### ISSUE TITLE
'jag monitor' should automatically decode stack traces

### ISSUE THREAD

**Issue by mikkeldamsgaard** [toitlang/jaguar#132]
It should be possible for jag monitor to automatically intercept (manual) stack trace output and convert it to a proper stack trace in the console

**Comment by kasperl** [comment]
This is a good idea. Maybe fixing the serial -> stdout path also allows us to fix the reported issue on Windows where `io.Copy` seems to buffer output.

Reported here: https://github.com/toitlang/toit/issues/457#issuecomment-1040926507.

**Comment by kasperl** [comment]
Fixed in #179.
