### ISSUE TITLE
Long device names look bad on Jaguar's device website

### ISSUE THREAD

**Issue by kasperl** [toitlang/jaguar#246]
If you point your browser to a Jaguar device's built-in HTTP server, you get a nice website (thanks, @nivoc!). However, if your device has a long name, it looks slightly less great:

![jaguar-webserver](https://user-images.githubusercontent.com/2156198/189473755-39ed3f95-5145-41f4-bf75-77cb8fd0301c.png)

**Comment by nivoc** [comment]
I'll have a look
