### ISSUE TITLE
Support developing applications that use triggers (timed sleep, GPIO wakeups)

### ISSUE THREAD

**Issue by krzychb** [toitlang/jaguar#27]
Resetting the device causes it to forget about the installed application. It is still in flash though, so we could change the code to find it there (maybe keep track of its position in NVS?) and automatically start it. 

Ideally, the application would use triggers from .yaml file - https://docs.toit.io/platform/apps/appspec/#the-specification-file

Inspired by https://esp32.com/viewtopic.php?f=2&t=24941#p88621

**Comment by kasperl** [comment]
It would make sense to implement a way to restart the last installed app to make testing of 'deep sleep' and GPIO-based wakeup behavior possible.

Jaguar is primarily thought of as a development (not deployment) framework, so more complex deployment support with .yaml files, etc. might be out of the initial scope.

**Comment by kasperl** [comment]
I think we can get pretty far by storing the last program (offset, size) in `device.FlashStore` and re-run it on boot. Maybe something for you, @lask?

We should make sure to clear the program before we kill it and (potentially) overwrite it in flash. And we should write the last program information just before starting the program when everything is ready to go.
