### ISSUE TITLE
Support getting wifi configuration

### ISSUE THREAD

**Issue by addshore** [toitlang/jaguar#561]
We have a device which has had a wifi config set, we would like to retrieve the config to see what has been set (primmarily to compare the settings to another ESP device).

a `jag config wifi get` command would be appreciated if possible.

**Comment by kasperl** [comment]
How would you like to retrieve the config? It is possible to access the wifi configuration from code on the device, but it sounds like maybe you need `jag config wifi get` to talk to the device without necessarily being on the same network.

**Comment by floitsch** [comment]
The `jag config` commands only work locally. You could just look at the configuration file in `$HOME/.config/jaguar/config`.

If you have access to the device through Jaguar you could run a program that gets it from the device: 

```
import system.firmware

main:
  print firmware.config["wifi"]
```

**Comment by addshore** [comment]
You are both correct indeed, 

This is probably answer enough for me!

> If you have access to the device through Jaguar you could run a program that gets it from the device:
> 
> ```
> import system.firmware
> 
> main:
>   print firmware.config["wifi"]
> ```
